name: Weekly Vivenu Report

on:
  schedule:
    - cron: '0 17 * * 1'  
  workflow_dispatch:    # allow manual run from GitHub

jobs:
  weekly-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Vivenu report script
        env:
          VIVENU_API_KEY: ${{ secrets.VIVENU_API_KEY }}
          OUTLOOK_CLIENT_ID: ${{ secrets.OUTLOOK_CLIENT_ID }}
          OUTLOOK_TENANT_ID: ${{ secrets.OUTLOOK_TENANT_ID }}
          OUTLOOK_CLIENT_SECRET: ${{ secrets.OUTLOOK_CLIENT_SECRET }}
          OUTLOOK_USER_EMAIL: ${{ secrets.OUTLOOK_USER_EMAIL }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
          SHOPIFY_SHOP_NAME: ${{ secrets.SHOPIFY_SHOP_NAME }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          API_VERSION: "2024-01"
        run: python main.py